export const titles={
    "/":"Home",
    "/about":"About Us",
    "/contacts":"Contact Us",
    "/services":"Our Services",
    "/services/Product_Sourcing":"Product Sourcing",
    "/services/Custom_Branding":"Custom Branding",  
    "/services/Fast_Shipping":"Fast Shipping",
    "/services/Inventary_Management":"Inventary Management",
    "/services/Support":"24*7 Support",
    "/services/Faq":"FAQ's",
    "/services/Livechat":"Live chat",
    "/services/Request_callback":"Request Callback",
    "/services/Emailsupport":"Email Support",
    "/help":"help",
    "/products":"Products",
    "/login":"Login Page",
    "/signin":"Signin Page",
    "cart":"Cart",
}