export const category=[
    "Technology",
  "Lifestyle",
  "Health & Fitness",
  "Travel",
  "Education",
  "Finance",
  "Food",
  "Fashion",
  "Entertainment",
  "Productivity",
  "News & Politics",
  "Business",
  "Self-Development",
  "Parenting",
  "Coding/Development",
  "UX/UI Design",
  "Photography",
  "Books & Reviews",
  "Spirituality",
  "Career Advice",
  "AI & Machine Learning",
  "Marketing & SEO",
  "Open Source Projects",
  "Remote Work",
  "Freelancing"
];